name: Hello World
on:
  push:
    branches: [ main ]
jobs:
  Mi-primer-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
    - name: Print 
      env:
        MI_VARIABLE: Hello World
      run: |
        echo $MI_VARIABLE.
